### ISSUE TITLE
File pinning as part of the lite version

### ISSUE THREAD

**Issue by cusspvz** [hsanjuan/ipfs-lite#132]
I'm assuming this implementation still keeps a repo (assuming by the datastore requirement). Doest it make sense to include the GC and the pinning/unpinning methods?

There might be cases where an application might want to retain the files besides adding to/ retrieving from network.

Would that be something to consider including into a Lite version?

**Comment by hsanjuan** [comment]
I have asked myself this question sometimes, and I think ipfs-lite should not include pinning functionality inside, primarily because this can be built on top when needed with ease. A `Pinner`  takes a Datastore (also needed to initialize ipfs-lite) and a DAGService (ipfs-lite itself):

https://pkg.go.dev/github.com/ipfs/go-ipfs-pinner@v0.1.1/dspinner#New

GC code is in go-ipfs: https://github.com/ipfs/go-ipfs/blob/master/gc/gc.go and it is very simple and directly usable as well.
